compose in jenkinsfile

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -109,7 +109,12 @@ pipeline {
                 dir('backend') {
                     sh '''
                     export JENKINS_NODE_COOKIE=dontKillMe
-                    sudo -u vinay-v-bhandare pkill -f app.py || true
+                    # Robust port cleanup: Check if port 5001 is busy, then kill it
+                    if sudo lsof -Pi :5001 -sTCP:LISTEN -t > /dev/null ; then
+                        echo "Port 5001 is currently occupied. Clearing it now..."
+                        sudo fuser -k 5001/tcp || true
+                        sleep 2
+                    fi
                     
                     # start backend in background as the local user so it has kubectl rights
                     sudo -E -u vinay-v-bhandare bash -c "nohup /var/lib/jenkins/workspace/spe_project_pipeline/backend/venv/bin/python /var/lib/jenkins/workspace/spe_project_pipeline/backend/app.py > /tmp/backend.log 2>&1 &"
